# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4afd1ab6794ef1cd026dc027e678d2a7b4380b565ddc01f0294d3371d2746e4e74d588c8b59dc12dee12164edf421b2ca55c133c9527e3f4daff82c6035f06f

test:
  secret_key_base: 9f27080f5615048c2951bf1507c0b2f157561401f8f631f553faccafe239a923b5e0d5198a8463986fbfa5b0e61812a648161abd99be1ef45445718fccd6352d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
